In [2]:
import numpy as np

x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(x)
print(y)

[[4 5 2]
 [7 8 5]
 [2 4 2]]
[[3 3 4]
 [7 1 6]
 [2 7 3]]


In [4]:
ans = x - y
print(ans)

[[ 1  2 -2]
 [ 0  7 -1]
 [ 0 -3 -1]]


In [5]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3))
print(x)
print(y)

[[7 7 5]
 [9 4 2]
 [5 7 5]]
[1 6 7]


In [6]:
ans = x - y
print(ans)

[[ 6  1 -2]
 [ 8 -2 -5]
 [ 4  1 -2]]


In [7]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))
print(x)
print(y)

[[3 4]
 [1 3]
 [7 7]]
[[1 2 4]
 [6 4 6]]


In [9]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[1 6]
 [2 4]
 [4 6]]
[[ 2 -2]
 [-1 -1]
 [ 3  1]]
