In [4]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [6]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [7]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [8]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [10]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
b = np.full((3, 3), 5, dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [15]:
a = np.empty(4, dtype = int)
a

array([2305843009213693952, 2305851779254794274, 3458773283861626882,
           562949953421312])