In [8]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 2 11  9 15 19]
[12 11 11  4 16]


In [10]:
li = [i+1 for i in li]
li

[3, 4, 5, 6, 7]

In [17]:
a = a + 1
a

array([ 7, 16, 14, 20, 24])

In [19]:
c = a + b
c

array([19, 27, 25, 24, 40])

In [20]:
d = a - b
d


array([-5,  5,  3, 16,  8])

In [22]:
e = a * b
e

array([ 84, 176, 154,  80, 384])

In [23]:
f = a / b
f

array([ 0.58333333,  1.45454545,  1.27272727,  5.        ,  1.5       ])

In [24]:
g = a // b
g

array([0, 1, 1, 5, 1])

In [25]:
h = a ** b
h

array([         13841287201,       17592186044416,        4049565169664,
                     160000, -2936065482068852736])

In [32]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 7 16 14 20 24]
81
16.2
7
0
24
4


In [34]:
print(a)
print(b)

[ 7 16 14 20 24]
[12 11 11  4 16]


In [36]:
a > b

array([False,  True,  True,  True,  True], dtype=bool)

In [37]:
a < b

array([ True, False, False, False, False], dtype=bool)

In [38]:
a == b

array([False, False, False, False, False], dtype=bool)

In [40]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))


[ True  True  True  True  True]
[ True  True  True  True  True]


In [42]:
a[2] = 0
print(a)
print(np.logical_not(a))

[ 7 16  0 20 24]
[False False  True False False]
