In [17]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [42]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [45]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [49]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [53]:
b = np.zeros((3, 4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [57]:
b = np.full((3, 3), 5, dtype = float)
b

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])