# Palindrome

In [2]:
from sys import stdin
def isPalindrome(string):
    # Your code goes here
    x = len(string)
    for i in range (0, x):
        if string[i] != string[-(i + 1)]:
            return False
    return True

#main
string = stdin.readline().strip()
ans = isPalindrome(string)

if ans:
    print('true')
else:
    print('false')

true


In [4]:
from sys import stdin


def printSubstrings(string) :
    # Your code goes here
    x = len(string)
    for i in range (0, x):
        for j in range (i, x):
            print (string[i:j])


#main
string = stdin.readline().strip();
printSubstrings(string)

# Dictionary

Different Names
Send Feedback
In Little Flowers Public School, there are many students with same first names. You are given a task to find the students with same names. You will be given a string comprising of all the names of students and you have to tell the name and count of those students having same. If all the names are unique, print -1 instead. <br>
Note: We don't have to mention names whose frequency is 1. <br>
Input Format:<br>
The only line of input will have a string ‘str’ with space separated first names of students.<br>
Output Format:<br>
Print the names of students along with their count if they are repeating. If no name is repeating, print -1<br>
Constraints:<br>
1 <= |str| <= 10^5<br>
Time Limit: 1 second<br>
Sample Input 1:<br>
Abhishek harshit Ayush harshit Ayush Iti Deepak Ayush Iti<br>
Sample Output 1:<br>
harshit 2<br>
Ayush 3<br>
Iti 2<br>
Sample Input 2:<br>
Abhishek Harshit Ayush Iti<br>
Sample Output:<br>
-1<br>

In [4]:
def differentNames(l):
    # Please add your code here
    d = {}
    for name in l:
        d[name] = d.get(name, 0) + 1
    for n in d:
        if d[n] > 1:
            print (n, d[n])
    return d
    pass

# Main
names = input().strip().split()
m = differentNames(names)

asa li asa li as a k k
asa 2
li 2
k 2


You are provided with an integer array where each number is present either odd number of times or even number of times. You have to find and return the number which is present even number of times. <br>
If multiple numbers are present even number of times, then return that number which occurs first among these numbers in the given array. If no such number exists, then return -1.

In [5]:
def evenCount(arr):
    d = {}
    for i in arr:
        d[i] = d.get(i, 0) + 1
    
    for i in arr:
        if not(d[i] % 2):
            return i
            
    pass

# Main
n=int(input())
arr=list(int(i) for i in input().strip().split(' '))
print(evenCount(arr))

1
1
None


In [ ]:
import operator

def fact (n):
    if n < 1:
        return 0
    if n == 1:
        return 1
    return n * fact(n - 1)

def printPairDiffK(l, k):
    #############################
    # PLEASE ADD YOUR CODE HERE #
    #############################
    counter = 0
    d = {}
    for i in l:
        d[i] = d.get(i, 0) + 1
        
    for i in d:
        diff1 = i - k
        diff2 = i + k
        # print( diff2)
        # print(d)
        if diff1 in d and d[i] > 0:
             if i == diff2:
                d[i] -= 1
                # print(d[i])
                counter += fact(d[i])
             else:
                counter = counter + (d[diff1] * d[i])
        if diff2 in d and d[i] > 0:
            if i == diff2:
                d[i] -= 1
                # print(d[i])
                counter += fact(d[i])
            else:
                counter = counter + (d[diff2] * d[i])
        d[i] = 0
    return counter
    
# Main
n=int(input())
l=list(int(i) for i in input().strip().split(' '))
k=int(input())
print(printPairDiffK(l, k))

In [3]:
class Student:
    def __init__(self,name,age):
        self.name = "Rohan"
        self.age = 20

    def print_student_details(self):
        print(self.name, end= " ")
        print(self.age)
        
s = Student("Parikh",25)
s.print_student_details()

Rohan 20


In [10]:
class A:
     def __init__(self):
         self.x = 1
         self.__y = 1
     def getY(self):
         return self.__y
a = A()
a.__y = 45
print(a.getY())

1


In [12]:
a.x
a.__y

45

In [27]:
class Student:
     def __init__(self,name,age):
        self.__name = name
        self.age = age
     def getName (self):
        return self.__name
     def print_student_details(self):
        print(self.__name, end= " ")
        print(self.age)

s = Student("R",20)
print(s.getName())
s.print_student_details()

R
R 20


In [3]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input_)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
for i in input_[2, 0:3]:
    print(i, end = " ")
print()
for i in input_[1:, 3]:
    print(i, end = " ")
print()
for i in input_[2:]:
    for j in i:
        print(j, end = " ")
print()
for i in input_[1:3, 1:3]:
    for j in i:
        print(j, end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [10]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

b = np.array([1,2,0,0,4,0])
bool_arr = np.where(b > 0)
print(bool_arr)
for i in bool_arr:
    for j in i:
        print (j, end = " ")

(array([0, 1, 4]),)
0 1 4 

In [13]:
# Given an integer array of size 10. Print the index of elements which are multiple of 3.


import numpy as np

array = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
three_multiple = np.where(array % 3 == 0)
for i in three_multiple:
    for j in i:
        print(j, end = " ")

1 4 7 

In [15]:
# Problem Statemnt:
# Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
# Note: Generate the following array
# array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Print the Numpy array.
# Output Format :
# firstElement secondElement  ... 

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[array % 2 == 1] = -1
for i in array:
    print(i, end = " ")

-1 2 -1 4 -1 6 -1 8 -1 10 

In [18]:
# Problem Statemnt:
# Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
# Note: Generate the following array
# array([11, 2, 13, 4, 15, 6, 27, 8, 19])
# Print the Numpy array.
# Output Format :
# firstElement
# secondElement 
# ... 
import numpy as np
array = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
array[array.argmax()] = 0
for i in array:
    print(i)

11
2
13
4
15
6
0
8
19


In [21]:
# Problem Statemnt:
# Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
# Note: Generate the following array
# array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Print the Numpy array.
# Output Format :
# firstElement 
# secondElement  
# ... 
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[2:8] = -array[2:8]
for i in array:
    print (i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [45]:
# Problem Statemnt:
# Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
# Print the Numpy array.
# Output Format :
# age1 height1 
# age2 height2 
# ... 

import numpy as np
age = np.array ([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height = np.array ([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

index=np.where(height>155)
# print(index)
for i in index:
    for j in i:
        print (age[j], height[j])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [72]:
import numpy as np

arr = np.array( [[21, 20, 19, 18, 17], [16, 15, 14, 13, 12], [11, 10,  9,  8,  7], [6,  5,  4,  3,  2]])
print('[', end = "")
for i in range(len(arr)):
    bool_ele = arr[i:, 1].argmin()
#     print(bool_ele)
    x = []
    x = arr[bool_ele]
    if i == 0:
        print('[ ', end = "")
        for i in range(len(x)):
            if i == len(x) - 1:
                print(x[i], end = "")
            else:
                print (x[i], end=" ")
        print(']')
    elif i == len(arr) - 1:
        print('[', end = "")
        for i in range(len(x)):
            if i == len(x) - 1:
                print(x[i], end = "")
            else:
                print (x[i], end=" ")
        print(']', end = "")
    else:
        print('[', end = "")
        for i in range(len(x)):
            if i == len(x) - 1:
                print(x[i], end = "")
            else:
                print (x[i], end=" ")
        print(']')
#     arr[bool_ele] = arr[i]
#     arr[i] = x
print(']')
#     arr[i], arr[bool_ele] = arr[bool_ele], arr[i]
# print (arr)

[[ 6 5 4 3 2]
[11 10 9 8 7]
[16 15 14 13 12]
[21 20 19 18 17]]
